<?php

namespace Database\Seeders;

use App\Models\Project;
use App\Models\MediaManager;
use App\Models\SystemSetting;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class AiImageGenerateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $aiApplications = array(
            array('id' => '175','entity' => 'ai_image_section_1_image','value' => '56','created_at' => '2024-03-20 10:21:30','updated_at' => '2024-03-20 10:21:30','deleted_at' => NULL),
            array('id' => '176','entity' => 'ai_image_section_1_title','value' => 'Dall-E 2 Image Generator','created_at' => '2024-03-20 10:21:30','updated_at' => '2024-03-20 10:21:30','deleted_at' => NULL),
            array('id' => '177','entity' => 'ai_image_section_1_short_description','value' => 'Generate Image using OpenAi dall-e 2 Features','created_at' => '2024-03-20 10:21:30','updated_at' => '2024-03-20 10:21:30','deleted_at' => NULL),
            array('id' => '178','entity' => 'ai_image_section_2_image','value' => '54','created_at' => '2024-03-20 10:21:30','updated_at' => '2024-03-20 10:21:30','deleted_at' => NULL),
            array('id' => '179','entity' => 'ai_image_section_2_title','value' => 'Stable Diffusion','created_at' => '2024-03-20 10:21:30','updated_at' => '2024-03-20 10:21:30','deleted_at' => NULL),
            array('id' => '180','entity' => 'ai_image_section_2_short_description','value' => 'Stable Diffusion is a deep learning, text-to-image model released in 2022 based on diffusion techniques.','created_at' => '2024-03-20 10:21:30','updated_at' => '2024-03-20 10:21:30','deleted_at' => NULL),
            array('id' => '181','entity' => 'ai_image_section_3_image','value' => '55','created_at' => '2024-03-20 10:21:30','updated_at' => '2024-03-20 10:21:30','deleted_at' => NULL),
            array('id' => '182','entity' => 'ai_image_section_3_title','value' => 'Dall-E 3 Image Generator','created_at' => '2024-03-20 10:21:30','updated_at' => '2024-03-20 10:21:30','deleted_at' => NULL),
            array('id' => '183','entity' => 'ai_image_section_3_short_description','value' => 'Generate High Quality Image using OpenAi dall-e 3 Features','created_at' => '2024-03-20 10:21:30','updated_at' => '2024-03-20 10:21:35','deleted_at' => NULL),
        );
        foreach ($aiApplications as $tool) {
            $setting = SystemSetting::where('entity', $tool['entity'])->first();
            if ($setting != null) {
                $setting->value = $tool['value'];
                $setting->save();
            } else {
                $setting = new SystemSetting;
                $setting->entity = $tool['entity'];
                $setting->value = $tool['value'];
                $setting->save();
            }
        }
        $projects = array(
            array('id' => '1', 'user_id' => '1', 'folder_id' => NULL, 'template_id' => NULL, 'custom_template_id' => NULL, 'model_name' => NULL, 'title' => 'popular-post-10.png', 'slug' => 'popular-post-10.png-fgqyl', 'content' => 'uploads/media/YmXrreIeXCCjjROng5N58MnZFB7AycRvQZgdQcPH.png', 'prompts' => NULL, 'completion' => NULL, 'words' => NULL, 'content_type' => 'image', 'resolution' => NULL, 'audio_file' => NULL, 'text_to_speech_content' => NULL, 'created_at' => '2024-03-20 10:24:05', 'updated_at' => '2024-03-20 10:24:05', 'deleted_at' => NULL, 'engine' => 'local', 'storage_type' => 'local', 'input_prompt' => NULL, 'completion_tokens' => NULL, 'is_published' => '1'),
            array('id' => '2', 'user_id' => '1', 'folder_id' => NULL, 'template_id' => NULL, 'custom_template_id' => NULL, 'model_name' => NULL, 'title' => 'popular-post-9.png', 'slug' => 'popular-post-9.png-ounev', 'content' => 'uploads/media/eIzd6hHZOalcnwrPMqaHU7AqQuZqjY05u8pIoxHn.png', 'prompts' => NULL, 'completion' => NULL, 'words' => NULL, 'content_type' => 'image', 'resolution' => NULL, 'audio_file' => NULL, 'text_to_speech_content' => NULL, 'created_at' => '2024-03-20 10:24:05', 'updated_at' => '2024-03-20 10:24:05', 'deleted_at' => NULL, 'engine' => 'local', 'storage_type' => 'local', 'input_prompt' => NULL, 'completion_tokens' => NULL, 'is_published' => '1'),
            array('id' => '3', 'user_id' => '1', 'folder_id' => NULL, 'template_id' => NULL, 'custom_template_id' => NULL, 'model_name' => NULL, 'title' => 'popular-post-11.png', 'slug' => 'popular-post-11.png-2khjt', 'content' => 'uploads/media/z6ghEhPROsxDnURSgtpNo83eBmhBMkbG5ezD5M3E.png', 'prompts' => NULL, 'completion' => NULL, 'words' => NULL, 'content_type' => 'image', 'resolution' => NULL, 'audio_file' => NULL, 'text_to_speech_content' => NULL, 'created_at' => '2024-03-20 10:24:05', 'updated_at' => '2024-03-20 10:24:05', 'deleted_at' => NULL, 'engine' => 'local', 'storage_type' => 'local', 'input_prompt' => NULL, 'completion_tokens' => NULL, 'is_published' => '1'),
            array('id' => '4', 'user_id' => '1', 'folder_id' => NULL, 'template_id' => NULL, 'custom_template_id' => NULL, 'model_name' => NULL, 'title' => 'popular-post-5.png', 'slug' => 'popular-post-5.png-wnwzx', 'content' => 'uploads/media/1DLUMsmNyGy8PeF50xteMxGUSQI2AoBkVMdFKV1M.png', 'prompts' => NULL, 'completion' => NULL, 'words' => NULL, 'content_type' => 'image', 'resolution' => NULL, 'audio_file' => NULL, 'text_to_speech_content' => NULL, 'created_at' => '2024-03-20 10:24:05', 'updated_at' => '2024-03-20 10:24:05', 'deleted_at' => NULL, 'engine' => 'local', 'storage_type' => 'local', 'input_prompt' => NULL, 'completion_tokens' => NULL, 'is_published' => '1'),
            array('id' => '5', 'user_id' => '1', 'folder_id' => NULL, 'template_id' => NULL, 'custom_template_id' => NULL, 'model_name' => NULL, 'title' => 'popular-post-4.png', 'slug' => 'popular-post-4.png-do5ay', 'content' => 'uploads/media/MLz5akOToNx4ET1T4CojXeEvu9WH6QhgP9cOhY1O.png', 'prompts' => NULL, 'completion' => NULL, 'words' => NULL, 'content_type' => 'image', 'resolution' => NULL, 'audio_file' => NULL, 'text_to_speech_content' => NULL, 'created_at' => '2024-03-20 10:24:05', 'updated_at' => '2024-03-20 10:24:05', 'deleted_at' => NULL, 'engine' => 'local', 'storage_type' => 'local', 'input_prompt' => NULL, 'completion_tokens' => NULL, 'is_published' => '1'),
            array('id' => '6', 'user_id' => '1', 'folder_id' => NULL, 'template_id' => NULL, 'custom_template_id' => NULL, 'model_name' => NULL, 'title' => 'popular-post-3.png', 'slug' => 'popular-post-3.png-a1yd2', 'content' => 'uploads/media/T4Vzc5QJ3ya77Z4IOcwHocZUxIxsaNiEeEOFGCim.png', 'prompts' => NULL, 'completion' => NULL, 'words' => NULL, 'content_type' => 'image', 'resolution' => NULL, 'audio_file' => NULL, 'text_to_speech_content' => NULL, 'created_at' => '2024-03-20 10:24:05', 'updated_at' => '2024-03-20 10:24:05', 'deleted_at' => NULL, 'engine' => 'local', 'storage_type' => 'local', 'input_prompt' => NULL, 'completion_tokens' => NULL, 'is_published' => '1'),
            array('id' => '7', 'user_id' => '1', 'folder_id' => NULL, 'template_id' => NULL, 'custom_template_id' => NULL, 'model_name' => NULL, 'title' => 'popular-post-2.png', 'slug' => 'popular-post-2.png-5mopa', 'content' => 'uploads/media/rgD3lq6imYfhJEsTF5EZd69ht3VnbPb3ITxiEDPM.png', 'prompts' => NULL, 'completion' => NULL, 'words' => NULL, 'content_type' => 'image', 'resolution' => NULL, 'audio_file' => NULL, 'text_to_speech_content' => NULL, 'created_at' => '2024-03-20 10:24:05', 'updated_at' => '2024-03-20 10:24:05', 'deleted_at' => NULL, 'engine' => 'local', 'storage_type' => 'local', 'input_prompt' => NULL, 'completion_tokens' => NULL, 'is_published' => '1'),
            array('id' => '8', 'user_id' => '1', 'folder_id' => NULL, 'template_id' => NULL, 'custom_template_id' => NULL, 'model_name' => NULL, 'title' => 'popular-post-6.png', 'slug' => 'popular-post-6.png-8yzal', 'content' => 'uploads/media/AbWfW3NOns772PGy2pL6pe8u1vXVWVFStUMqowol.png', 'prompts' => NULL, 'completion' => NULL, 'words' => NULL, 'content_type' => 'image', 'resolution' => NULL, 'audio_file' => NULL, 'text_to_speech_content' => NULL, 'created_at' => '2024-03-20 10:24:05', 'updated_at' => '2024-03-20 10:24:05', 'deleted_at' => NULL, 'engine' => 'local', 'storage_type' => 'local', 'input_prompt' => NULL, 'completion_tokens' => NULL, 'is_published' => '1'),
            array('id' => '9', 'user_id' => '1', 'folder_id' => NULL, 'template_id' => NULL, 'custom_template_id' => NULL, 'model_name' => NULL, 'title' => 'insight-3.png', 'slug' => 'insight-3.png-dl9ku', 'content' => 'uploads/media/lhAEEpt9G0pMdZfAH6spBcr7rYtEphF9bVThs1FR.png', 'prompts' => NULL, 'completion' => NULL, 'words' => NULL, 'content_type' => 'image', 'resolution' => NULL, 'audio_file' => NULL, 'text_to_speech_content' => NULL, 'created_at' => '2024-03-20 10:24:05', 'updated_at' => '2024-03-20 10:24:05', 'deleted_at' => NULL, 'engine' => 'local', 'storage_type' => 'local', 'input_prompt' => NULL, 'completion_tokens' => NULL, 'is_published' => '1'),
            array('id' => '10', 'user_id' => '1', 'folder_id' => NULL, 'template_id' => NULL, 'custom_template_id' => NULL, 'model_name' => NULL, 'title' => 'insight-2.png', 'slug' => 'insight-2.png-kow38', 'content' => 'uploads/media/ejOyRxBK6P3kE6Vr7e9FTduGhTwJ4RCKangRzEbK.png', 'prompts' => NULL, 'completion' => NULL, 'words' => NULL, 'content_type' => 'image', 'resolution' => NULL, 'audio_file' => NULL, 'text_to_speech_content' => NULL, 'created_at' => '2024-03-20 10:24:05', 'updated_at' => '2024-03-20 10:24:05', 'deleted_at' => NULL, 'engine' => 'local', 'storage_type' => 'local', 'input_prompt' => NULL, 'completion_tokens' => NULL, 'is_published' => '1'),
            array('id' => '11', 'user_id' => '1', 'folder_id' => NULL, 'template_id' => NULL, 'custom_template_id' => NULL, 'model_name' => NULL, 'title' => 'ai-image-slide-5.png', 'slug' => 'ai-image-slide-5.png-hmlmy', 'content' => 'uploads/media/76CwWSrcqNpKwOC4xyBdIcLaqHPZkfvGZXYjO93y.png', 'prompts' => NULL, 'completion' => NULL, 'words' => NULL, 'content_type' => 'image', 'resolution' => NULL, 'audio_file' => NULL, 'text_to_speech_content' => NULL, 'created_at' => '2024-03-20 10:24:05', 'updated_at' => '2024-03-20 10:24:05', 'deleted_at' => NULL, 'engine' => 'local', 'storage_type' => 'local', 'input_prompt' => NULL, 'completion_tokens' => NULL, 'is_published' => '1'),
            array('id' => '12', 'user_id' => '1', 'folder_id' => NULL, 'template_id' => NULL, 'custom_template_id' => NULL, 'model_name' => NULL, 'title' => 'popular-post-1.png', 'slug' => 'popular-post-1.png-rvaeq', 'content' => 'uploads/media/NpyhziYxqZfYX1hrPCPDLLDgv5ZvqJT5GzahL6yt.png', 'prompts' => NULL, 'completion' => NULL, 'words' => NULL, 'content_type' => 'image', 'resolution' => NULL, 'audio_file' => NULL, 'text_to_speech_content' => NULL, 'created_at' => '2024-03-20 10:24:05', 'updated_at' => '2024-03-20 10:24:05', 'deleted_at' => NULL, 'engine' => 'local', 'storage_type' => 'local', 'input_prompt' => NULL, 'completion_tokens' => NULL, 'is_published' => '1'),
            array('id' => '13', 'user_id' => '1', 'folder_id' => NULL, 'template_id' => NULL, 'custom_template_id' => NULL, 'model_name' => NULL, 'title' => 'ai-featured-video-img-3.png', 'slug' => 'ai-featured-video-img-3.png-00uke', 'content' => 'uploads/media/BUtcZ68o5zpNANxj38HNmI7R4mDfFEWGbhS4y4M8.png', 'prompts' => NULL, 'completion' => NULL, 'words' => NULL, 'content_type' => 'image', 'resolution' => NULL, 'audio_file' => NULL, 'text_to_speech_content' => NULL, 'created_at' => '2024-03-20 10:24:05', 'updated_at' => '2024-03-20 10:24:05', 'deleted_at' => NULL, 'engine' => 'local', 'storage_type' => 'local', 'input_prompt' => NULL, 'completion_tokens' => NULL, 'is_published' => '1'),
            array('id' => '14', 'user_id' => '1', 'folder_id' => NULL, 'template_id' => NULL, 'custom_template_id' => NULL, 'model_name' => NULL, 'title' => 'ai-featured-video-img-2.png', 'slug' => 'ai-featured-video-img-2.png-ksrj3', 'content' => 'uploads/media/vMZ95Vilv0Qi6qO4rbx20fHPQurfzabU9HPjoE3c.png', 'prompts' => NULL, 'completion' => NULL, 'words' => NULL, 'content_type' => 'image', 'resolution' => NULL, 'audio_file' => NULL, 'text_to_speech_content' => NULL, 'created_at' => '2024-03-20 10:24:05', 'updated_at' => '2024-03-20 10:24:05', 'deleted_at' => NULL, 'engine' => 'local', 'storage_type' => 'local', 'input_prompt' => NULL, 'completion_tokens' => NULL, 'is_published' => '1'),
            array('id' => '15', 'user_id' => '1', 'folder_id' => NULL, 'template_id' => NULL, 'custom_template_id' => NULL, 'model_name' => NULL, 'title' => 'ai-image-slide-2.png', 'slug' => 'ai-image-slide-2.png-nhei6', 'content' => 'uploads/media/w1prPacnTuPvCdnmoKsf0olIi5sF2VxfNWiFsdqb.png', 'prompts' => NULL, 'completion' => NULL, 'words' => NULL, 'content_type' => 'image', 'resolution' => NULL, 'audio_file' => NULL, 'text_to_speech_content' => NULL, 'created_at' => '2024-03-20 10:24:05', 'updated_at' => '2024-03-20 10:24:05', 'deleted_at' => NULL, 'engine' => 'local', 'storage_type' => 'local', 'input_prompt' => NULL, 'completion_tokens' => NULL, 'is_published' => '1'),
            array('id' => '16', 'user_id' => '1', 'folder_id' => NULL, 'template_id' => NULL, 'custom_template_id' => NULL, 'model_name' => NULL, 'title' => 'ai-image-slide-6.png', 'slug' => 'ai-image-slide-6.png-h9xeq', 'content' => 'uploads/media/s6Cejmb02gSLbpOYiZzFQR3hlhkpwhyS4e1oIpNQ.png', 'prompts' => NULL, 'completion' => NULL, 'words' => NULL, 'content_type' => 'image', 'resolution' => NULL, 'audio_file' => NULL, 'text_to_speech_content' => NULL, 'created_at' => '2024-03-20 10:24:05', 'updated_at' => '2024-03-20 10:24:05', 'deleted_at' => NULL, 'engine' => 'local', 'storage_type' => 'local', 'input_prompt' => NULL, 'completion_tokens' => NULL, 'is_published' => '1'),
            array('id' => '17', 'user_id' => '1', 'folder_id' => NULL, 'template_id' => NULL, 'custom_template_id' => NULL, 'model_name' => NULL, 'title' => 'ai-image-slide-12.png', 'slug' => 'ai-image-slide-12.png-y5nt0', 'content' => 'uploads/media/92Rikf03wOrWggAeRm8PQCZfBzRtMJLBrwjAbTTU.png', 'prompts' => NULL, 'completion' => NULL, 'words' => NULL, 'content_type' => 'image', 'resolution' => NULL, 'audio_file' => NULL, 'text_to_speech_content' => NULL, 'created_at' => '2024-03-20 10:24:05', 'updated_at' => '2024-03-20 10:24:05', 'deleted_at' => NULL, 'engine' => 'local', 'storage_type' => 'local', 'input_prompt' => NULL, 'completion_tokens' => NULL, 'is_published' => '1'),
            array('id' => '18', 'user_id' => '1', 'folder_id' => NULL, 'template_id' => NULL, 'custom_template_id' => NULL, 'model_name' => NULL, 'title' => 'ai-image-slide-11.png', 'slug' => 'ai-image-slide-11.png-dlkax', 'content' => 'uploads/media/QMHd768U8eoUxuQoK2J9h1CupxsmXyxcE9XlfMFK.png', 'prompts' => NULL, 'completion' => NULL, 'words' => NULL, 'content_type' => 'image', 'resolution' => NULL, 'audio_file' => NULL, 'text_to_speech_content' => NULL, 'created_at' => '2024-03-20 10:24:05', 'updated_at' => '2024-03-20 10:24:05', 'deleted_at' => NULL, 'engine' => 'local', 'storage_type' => 'local', 'input_prompt' => NULL, 'completion_tokens' => NULL, 'is_published' => '1'),
            array('id' => '19', 'user_id' => '1', 'folder_id' => NULL, 'template_id' => NULL, 'custom_template_id' => NULL, 'model_name' => NULL, 'title' => 'ai-image-slide-10.png', 'slug' => 'ai-image-slide-10.png-zul6k', 'content' => 'uploads/media/7Quhoi9MaqmENZ6hQjnkyUuMkCyge70ZPbJdQ7zk.png', 'prompts' => NULL, 'completion' => NULL, 'words' => NULL, 'content_type' => 'image', 'resolution' => NULL, 'audio_file' => NULL, 'text_to_speech_content' => NULL, 'created_at' => '2024-03-20 10:24:05', 'updated_at' => '2024-03-20 10:24:05', 'deleted_at' => NULL, 'engine' => 'local', 'storage_type' => 'local', 'input_prompt' => NULL, 'completion_tokens' => NULL, 'is_published' => '1'),
            array('id' => '20', 'user_id' => '1', 'folder_id' => NULL, 'template_id' => NULL, 'custom_template_id' => NULL, 'model_name' => NULL, 'title' => 'ai-image-slide-9.png', 'slug' => 'ai-image-slide-9.png-ts9fi', 'content' => 'uploads/media/LpfohnS7fNJ98uBaLyBB5lf8D0xZNO8R1SZL25bQ.png', 'prompts' => NULL, 'completion' => NULL, 'words' => NULL, 'content_type' => 'image', 'resolution' => NULL, 'audio_file' => NULL, 'text_to_speech_content' => NULL, 'created_at' => '2024-03-20 10:24:05', 'updated_at' => '2024-03-20 10:24:05', 'deleted_at' => NULL, 'engine' => 'local', 'storage_type' => 'local', 'input_prompt' => NULL, 'completion_tokens' => NULL, 'is_published' => '1'),
            array('id' => '21', 'user_id' => '1', 'folder_id' => NULL, 'template_id' => NULL, 'custom_template_id' => NULL, 'model_name' => NULL, 'title' => 'insight-1.png', 'slug' => 'insight-1.png-u9f6z', 'content' => 'uploads/media/CW4Mdr8igX30Q3m02ntRLAonfjig44K7SstXSQOx.png', 'prompts' => NULL, 'completion' => NULL, 'words' => NULL, 'content_type' => 'image', 'resolution' => NULL, 'audio_file' => NULL, 'text_to_speech_content' => NULL, 'created_at' => '2024-03-20 10:24:05', 'updated_at' => '2024-03-20 10:24:05', 'deleted_at' => NULL, 'engine' => 'local', 'storage_type' => 'local', 'input_prompt' => NULL, 'completion_tokens' => NULL, 'is_published' => '1'),
            array('id' => '22', 'user_id' => '1', 'folder_id' => NULL, 'template_id' => NULL, 'custom_template_id' => NULL, 'model_name' => NULL, 'title' => 'ai-image-slide-16.png', 'slug' => 'ai-image-slide-16.png-xm71e', 'content' => 'uploads/media/ffFR6R4lm6UlPiDs5kXbGUpFGrPawAIVM4N0ux3S.png', 'prompts' => NULL, 'completion' => NULL, 'words' => NULL, 'content_type' => 'image', 'resolution' => NULL, 'audio_file' => NULL, 'text_to_speech_content' => NULL, 'created_at' => '2024-03-20 10:24:05', 'updated_at' => '2024-03-20 10:24:05', 'deleted_at' => NULL, 'engine' => 'local', 'storage_type' => 'local', 'input_prompt' => NULL, 'completion_tokens' => NULL, 'is_published' => '1'),
            array('id' => '23', 'user_id' => '1', 'folder_id' => NULL, 'template_id' => NULL, 'custom_template_id' => NULL, 'model_name' => NULL, 'title' => 'ai-image-slide-15.png', 'slug' => 'ai-image-slide-15.png-zvmu1', 'content' => 'uploads/media/9WSCLmtY3vWtsK3Nt7R4UsLWEyXamk4M08qs1Kev.png', 'prompts' => NULL, 'completion' => NULL, 'words' => NULL, 'content_type' => 'image', 'resolution' => NULL, 'audio_file' => NULL, 'text_to_speech_content' => NULL, 'created_at' => '2024-03-20 10:24:05', 'updated_at' => '2024-03-20 10:24:05', 'deleted_at' => NULL, 'engine' => 'local', 'storage_type' => 'local', 'input_prompt' => NULL, 'completion_tokens' => NULL, 'is_published' => '1'),
            array('id' => '24', 'user_id' => '1', 'folder_id' => NULL, 'template_id' => NULL, 'custom_template_id' => NULL, 'model_name' => NULL, 'title' => 'ai-image-slide-13.png', 'slug' => 'ai-image-slide-13.png-hmqnz', 'content' => 'uploads/media/FlSHC8qUW5eVMOEWZc1jtJdwqeBQ8QNJWbPyXurI.png', 'prompts' => NULL, 'completion' => NULL, 'words' => NULL, 'content_type' => 'image', 'resolution' => NULL, 'audio_file' => NULL, 'text_to_speech_content' => NULL, 'created_at' => '2024-03-20 10:24:05', 'updated_at' => '2024-03-20 10:24:05', 'deleted_at' => NULL, 'engine' => 'local', 'storage_type' => 'local', 'input_prompt' => NULL, 'completion_tokens' => NULL, 'is_published' => '1'),
            array('id' => '25', 'user_id' => '1', 'folder_id' => NULL, 'template_id' => NULL, 'custom_template_id' => NULL, 'model_name' => NULL, 'title' => 'ai-featured-video-img-4.png', 'slug' => 'ai-featured-video-img-4.png-ha6vj', 'content' => 'uploads/media/8u8g3zdRrb6EbiuZ1msdRoavDmaxsUbIgylzb7Av.png', 'prompts' => NULL, 'completion' => NULL, 'words' => NULL, 'content_type' => 'image', 'resolution' => NULL, 'audio_file' => NULL, 'text_to_speech_content' => NULL, 'created_at' => '2024-03-20 10:24:05', 'updated_at' => '2024-03-20 10:24:05', 'deleted_at' => NULL, 'engine' => 'local', 'storage_type' => 'local', 'input_prompt' => NULL, 'completion_tokens' => NULL, 'is_published' => '1'),
            array('id' => '26', 'user_id' => '1', 'folder_id' => NULL, 'template_id' => NULL, 'custom_template_id' => NULL, 'model_name' => NULL, 'title' => 'ai-image-slide-1.png', 'slug' => 'ai-image-slide-1.png-pjoig', 'content' => 'uploads/media/qHVNZIW4EPy13v1TePIysBXpAqPWEihOS2owtJYg.png', 'prompts' => NULL, 'completion' => NULL, 'words' => NULL, 'content_type' => 'image', 'resolution' => NULL, 'audio_file' => NULL, 'text_to_speech_content' => NULL, 'created_at' => '2024-03-20 10:24:05', 'updated_at' => '2024-03-20 10:24:05', 'deleted_at' => NULL, 'engine' => 'local', 'storage_type' => 'local', 'input_prompt' => NULL, 'completion_tokens' => NULL, 'is_published' => '1')
        );
        foreach ($projects as $media) {
            $project = new Project;
            $project->user_id       = $media['user_id'];
            $project->title         = $media['title'];
            $project->slug          = $media['slug'];
            $project->content_type  = 'image';

            $project->content       = $media['content'];
            $project->engine        = 'local';
            $project->storage_type  = 'local';
            $project->is_published  = 1;
            $project->save();
        }
        $media_managers = array(
            array('id' => '33', 'user_id' => '1', 'media_file' => 'uploads/media/LYHIqdlUyNHWB5FWoWZKKxEbV8uSkfLtL7NEnXDy.png', 'media_size' => '697', 'media_type' => 'image', 'media_name' => 'ai-tools-card-img-1.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:27:27', 'updated_at' => '2024-03-20 09:27:27', 'deleted_at' => NULL),
            array('id' => '34', 'user_id' => '1', 'media_file' => 'uploads/media/mIeqkecZ94L5dLgEwUAIz37VzsBrmEWt1OQ3FwdM.png', 'media_size' => '37984', 'media_type' => 'image', 'media_name' => 'Storage Management.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:43', 'updated_at' => '2024-03-20 09:28:43', 'deleted_at' => NULL),
            array('id' => '35', 'user_id' => '1', 'media_file' => 'uploads/media/zGVMh8rb7HN3cYFcjL6XfS4mPynAnUKJVuXmA1xg.png', 'media_size' => '26104', 'media_type' => 'image', 'media_name' => 'Social Login.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:43', 'updated_at' => '2024-03-20 09:28:43', 'deleted_at' => NULL),
            array('id' => '36', 'user_id' => '1', 'media_file' => 'uploads/media/MqhdN3swXnuwjyPTi40HK5xHP29gvbquzm9mVOI8.png', 'media_size' => '2442', 'media_type' => 'image', 'media_name' => 'ai-tools-card-img-5.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:43', 'updated_at' => '2024-03-20 09:28:43', 'deleted_at' => NULL),
            array('id' => '37', 'user_id' => '1', 'media_file' => 'uploads/media/0SmgQ3IcyKR6tlCcppwkpRG0viECFMI1aY9inLQU.png', 'media_size' => '26601', 'media_type' => 'image', 'media_name' => 'Twilio Credentials.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:43', 'updated_at' => '2024-03-20 09:28:43', 'deleted_at' => NULL),
            array('id' => '38', 'user_id' => '1', 'media_file' => 'uploads/media/6ToWNneIyFmufGCRSjsU04q77SK3Sr3SUS9GCNrg.png', 'media_size' => '30195', 'media_type' => 'image', 'media_name' => 'Google (1).png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:43', 'updated_at' => '2024-03-20 09:28:43', 'deleted_at' => NULL),
            array('id' => '39', 'user_id' => '1', 'media_file' => 'uploads/media/U1NnEAd810RjAPzXNRLGz2BLDYTIyx5lPb8665IT.png', 'media_size' => '11361', 'media_type' => 'image', 'media_name' => 'ai-tools-card-img-2 (1).png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:44', 'updated_at' => '2024-03-20 09:28:44', 'deleted_at' => NULL),
            array('id' => '40', 'user_id' => '1', 'media_file' => 'uploads/media/4frGeilaXbpoXxcySkZtSH4SUkC7sBuVsF0HKvwS.png', 'media_size' => '1965', 'media_type' => 'image', 'media_name' => 'ai-application-icon-3.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:44', 'updated_at' => '2024-03-20 09:28:44', 'deleted_at' => NULL),
            array('id' => '41', 'user_id' => '1', 'media_file' => 'uploads/media/FKqPeC4XUlq5fhN7bq7Rt1REdfROkeGyULZ3ndYv.png', 'media_size' => '25156', 'media_type' => 'image', 'media_name' => 'affiliate marketing.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:44', 'updated_at' => '2024-03-20 09:28:44', 'deleted_at' => NULL),
            array('id' => '42', 'user_id' => '1', 'media_file' => 'uploads/media/sUD7MniXjChCU1HMQq2w9z2XUIByO8ud9Z2ZzRYi.png', 'media_size' => '1153', 'media_type' => 'image', 'media_name' => 'ai-application-icon-4.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:44', 'updated_at' => '2024-03-20 09:28:44', 'deleted_at' => NULL),
            array('id' => '43', 'user_id' => '1', 'media_file' => 'uploads/media/Wtd2ivUyWUe3vQAJP8IP2We8Xr01gX5RAeLhpOMy.png', 'media_size' => '261101', 'media_type' => 'image', 'media_name' => 'testimonial-4-shape-dots.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:44', 'updated_at' => '2024-03-20 09:28:44', 'deleted_at' => NULL),
            array('id' => '44', 'user_id' => '1', 'media_file' => 'uploads/media/BI6U0vYE0VtATR7YUXy85qeIWDx3wHwAUkiXvgq0.png', 'media_size' => '1873', 'media_type' => 'image', 'media_name' => 'ai-application-icon-2.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:44', 'updated_at' => '2024-03-20 09:28:44', 'deleted_at' => NULL),
            array('id' => '45', 'user_id' => '1', 'media_file' => 'uploads/media/8xCmOJIHloGGkA1KaRNQn1D67IDp7NgyJbGu4kjd.png', 'media_size' => '1778', 'media_type' => 'image', 'media_name' => 'ai-application-icon-1.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:44', 'updated_at' => '2024-03-20 09:28:44', 'deleted_at' => NULL),
            array('id' => '46', 'user_id' => '1', 'media_file' => 'uploads/media/oY0p5qYKwuCghptcfDYr4SrhIw3yxKfeYhWU1qFz.png', 'media_size' => '24201', 'media_type' => 'image', 'media_name' => 'AI PDF Chat.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:44', 'updated_at' => '2024-03-20 09:28:44', 'deleted_at' => NULL),
            array('id' => '47', 'user_id' => '1', 'media_file' => 'uploads/media/lyV6xTRnHNzjC0zUuVw8MAEpWUYEH0LlKnWa10DA.png', 'media_size' => '79987', 'media_type' => 'image', 'media_name' => 'AI VISION.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:45', 'updated_at' => '2024-03-20 09:28:45', 'deleted_at' => NULL),
            array('id' => '48', 'user_id' => '1', 'media_file' => 'uploads/media/u7Z7gTZdCNnRKSm8tGuWTJFDUxKTeC2KRdJpDe40.png', 'media_size' => '61002', 'media_type' => 'image', 'media_name' => 'AI Chat to image.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:45', 'updated_at' => '2024-03-20 09:28:45', 'deleted_at' => NULL),
            array('id' => '49', 'user_id' => '1', 'media_file' => 'uploads/media/ppP2H29Vcnd43Q3KY46XxnuBzjLBc194dXyCalgn.png', 'media_size' => '26503', 'media_type' => 'image', 'media_name' => 'AI Chat.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:45', 'updated_at' => '2024-03-20 09:28:45', 'deleted_at' => NULL),
            array('id' => '50', 'user_id' => '1', 'media_file' => 'uploads/media/7GPtw5YJS5HSZXxMiftBTWRiaUM8EkrCswvwKSq4.png', 'media_size' => '30979', 'media_type' => 'image', 'media_name' => 'azure.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:45', 'updated_at' => '2024-03-20 09:28:45', 'deleted_at' => NULL),
            array('id' => '51', 'user_id' => '1', 'media_file' => 'uploads/media/xqTwmjLyhxKOA62zQt8IPXXM4dyuB7M8amQaiaU4.png', 'media_size' => '10768', 'media_type' => 'image', 'media_name' => 'IIElevenlabs.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:45', 'updated_at' => '2024-03-20 09:28:45', 'deleted_at' => NULL),
            array('id' => '52', 'user_id' => '1', 'media_file' => 'uploads/media/n6BdfTgN7JaRKWG3UujL7MAWG5ukwJ0WIPJXcXPY.png', 'media_size' => '23124', 'media_type' => 'image', 'media_name' => 'Open AI.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:45', 'updated_at' => '2024-03-20 09:28:45', 'deleted_at' => NULL),
            array('id' => '53', 'user_id' => '1', 'media_file' => 'uploads/media/XEHWIW7ELu12jB7fsQv1kT6l19N7bLgoeLitOWep.png', 'media_size' => '12371', 'media_type' => 'image', 'media_name' => 'Google.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:45', 'updated_at' => '2024-03-20 09:28:45', 'deleted_at' => NULL),
            array('id' => '54', 'user_id' => '1', 'media_file' => 'uploads/media/vfVTApPecKb380ZX3TZifUZtDEFFaG8J3EYv5Pxv.png', 'media_size' => '23080', 'media_type' => 'image', 'media_name' => 'ai-image-card-2.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:45', 'updated_at' => '2024-03-20 09:28:45', 'deleted_at' => NULL),
            array('id' => '55', 'user_id' => '1', 'media_file' => 'uploads/media/fK5jk3Wyo7VaqtQatWUtUxdE4LhXpiZzaBXpJs4s.png', 'media_size' => '9609', 'media_type' => 'image', 'media_name' => 'ai-image-card-3.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:45', 'updated_at' => '2024-03-20 09:28:45', 'deleted_at' => NULL),
            array('id' => '56', 'user_id' => '1', 'media_file' => 'uploads/media/VeXX49YTJvxdAToyZOHANuOa4UzoNfEDgAnY9ZdU.png', 'media_size' => '13123', 'media_type' => 'image', 'media_name' => 'ai-image-card-1.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:45', 'updated_at' => '2024-03-20 09:28:45', 'deleted_at' => NULL),
            array('id' => '57', 'user_id' => '1', 'media_file' => 'uploads/media/nZUWEvvYh0PDFbJWuwc5EBSltIbY3SmsZ2xUu7ka.png', 'media_size' => '16977', 'media_type' => 'image', 'media_name' => 'Public Blog.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:45', 'updated_at' => '2024-03-20 09:28:45', 'deleted_at' => NULL),
            array('id' => '58', 'user_id' => '1', 'media_file' => 'uploads/media/D6AO0HT3Q1QyGQHR5w4FBAEcfPMhNOb4uYX63Qa0.png', 'media_size' => '31504', 'media_type' => 'image', 'media_name' => 'Create Outline.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:45', 'updated_at' => '2024-03-20 09:28:45', 'deleted_at' => NULL),
            array('id' => '59', 'user_id' => '1', 'media_file' => 'uploads/media/nwIDceo3SItd6Cu7EcqQQY2r3ZdVbIEcLlKYe2Dc.png', 'media_size' => '24715', 'media_type' => 'image', 'media_name' => 'AI BLOG (1).png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:46', 'updated_at' => '2024-03-20 09:28:46', 'deleted_at' => NULL),
            array('id' => '60', 'user_id' => '1', 'media_file' => 'uploads/media/kkU5aBM1vLUFeuIpjXAUPV4qbrOfN5S6moxJ9Ydt.png', 'media_size' => '22357', 'media_type' => 'image', 'media_name' => 'AI Full Blog.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:46', 'updated_at' => '2024-03-20 09:28:46', 'deleted_at' => NULL),
            array('id' => '61', 'user_id' => '1', 'media_file' => 'uploads/media/vaH1KHg5bv0A8edjRpmcoCttVjDXj9TxDeYvqLND.png', 'media_size' => '32665', 'media_type' => 'image', 'media_name' => 'Email Templated.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:46', 'updated_at' => '2024-03-20 09:28:46', 'deleted_at' => NULL),
            array('id' => '62', 'user_id' => '1', 'media_file' => 'uploads/media/Bu9UJiU4kzKLxSvmCGdY8Wuj897zunyrcbbJg0TW.png', 'media_size' => '25277', 'media_type' => 'image', 'media_name' => 'AI Blog.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:46', 'updated_at' => '2024-03-20 09:28:46', 'deleted_at' => NULL),
            array('id' => '63', 'user_id' => '1', 'media_file' => 'uploads/media/31FYJoAr89IelzAjbgDuBjkBVzM4iiFrfejdcQ3h.png', 'media_size' => '34508', 'media_type' => 'image', 'media_name' => 'Fun or Quote.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:46', 'updated_at' => '2024-03-20 09:28:46', 'deleted_at' => NULL),
            array('id' => '64', 'user_id' => '1', 'media_file' => 'uploads/media/NqvX51lSTzataYvD0pktquxbpFwnGtzlx7kLbYt2.png', 'media_size' => '22028', 'media_type' => 'image', 'media_name' => 'Social Media Templated.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:46', 'updated_at' => '2024-03-20 09:28:46', 'deleted_at' => NULL),
            array('id' => '65', 'user_id' => '1', 'media_file' => 'uploads/media/XLXUm4rUow6zmTvTEaVJYH4CyOy6xg1vrRKIkAx3.png', 'media_size' => '5797', 'media_type' => 'image', 'media_name' => 'ai-tools-card-img-4.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:46', 'updated_at' => '2024-03-20 09:28:46', 'deleted_at' => NULL),
            array('id' => '66', 'user_id' => '1', 'media_file' => 'uploads/media/wLOBj2qS9IzJTpOofmVWAtxIgrOLAcJSes3W6NDB.png', 'media_size' => '70105', 'media_type' => 'image', 'media_name' => 'map.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:46', 'updated_at' => '2024-03-20 09:28:46', 'deleted_at' => NULL),
            array('id' => '67', 'user_id' => '1', 'media_file' => 'uploads/media/2XgEhTjyVbV4Qp8spoWsZrWRY7S9JA1xD9sICU6S.png', 'media_size' => '22103', 'media_type' => 'image', 'media_name' => 'ai-tools-card-img-3-globe.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:46', 'updated_at' => '2024-03-20 09:28:46', 'deleted_at' => NULL),
            array('id' => '68', 'user_id' => '1', 'media_file' => 'uploads/media/3Fmyl2cMxv9WKnIq9KJ0KqTfOqmUVY58htSJdimN.png', 'media_size' => '11361', 'media_type' => 'image', 'media_name' => 'ai-tools-card-img-2.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:46', 'updated_at' => '2024-03-20 09:28:46', 'deleted_at' => NULL),
            array('id' => '69', 'user_id' => '1', 'media_file' => 'uploads/media/EZRK1vXhyBSsS5rx4Y5QGAfYzClfRhxAgq4V9qpO.png', 'media_size' => '5704', 'media_type' => 'image', 'media_name' => 'ai-tools-card-shape-1.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:28:46', 'updated_at' => '2024-03-20 09:28:46', 'deleted_at' => NULL),
            array('id' => '70', 'user_id' => '1', 'media_file' => 'uploads/media/bsixvuR7PtPwTsxo4WiRRwePxqBYrVtPjLhxZxCN.png', 'media_size' => '16967', 'media_type' => 'image', 'media_name' => 'affir.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:51:16', 'updated_at' => '2024-03-20 09:51:16', 'deleted_at' => NULL),
            array('id' => '71', 'user_id' => '1', 'media_file' => 'uploads/media/HBszinquVVNnE8VRJeXyaxEwwCnEk3uLkoYofmX3.png', 'media_size' => '17218', 'media_type' => 'image', 'media_name' => 'affir.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 09:52:22', 'updated_at' => '2024-03-20 09:52:22', 'deleted_at' => NULL),
            array('id' => '72', 'user_id' => '1', 'media_file' => 'uploads/media/qHVNZIW4EPy13v1TePIysBXpAqPWEihOS2owtJYg.png', 'media_size' => '36256', 'media_type' => 'image', 'media_name' => 'ai-image-slide-1.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:36', 'updated_at' => '2024-03-20 10:23:36', 'deleted_at' => NULL),
            array('id' => '73', 'user_id' => '1', 'media_file' => 'uploads/media/w1prPacnTuPvCdnmoKsf0olIi5sF2VxfNWiFsdqb.png', 'media_size' => '40999', 'media_type' => 'image', 'media_name' => 'ai-image-slide-2.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:36', 'updated_at' => '2024-03-20 10:23:36', 'deleted_at' => NULL),
            array('id' => '74', 'user_id' => '1', 'media_file' => 'uploads/media/BUtcZ68o5zpNANxj38HNmI7R4mDfFEWGbhS4y4M8.png', 'media_size' => '239877', 'media_type' => 'image', 'media_name' => 'ai-featured-video-img-3.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:36', 'updated_at' => '2024-03-20 10:23:36', 'deleted_at' => NULL),
            array('id' => '75', 'user_id' => '1', 'media_file' => 'uploads/media/vMZ95Vilv0Qi6qO4rbx20fHPQurfzabU9HPjoE3c.png', 'media_size' => '188633', 'media_type' => 'image', 'media_name' => 'ai-featured-video-img-2.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:36', 'updated_at' => '2024-03-20 10:23:36', 'deleted_at' => NULL),
            array('id' => '76', 'user_id' => '1', 'media_file' => 'uploads/media/8u8g3zdRrb6EbiuZ1msdRoavDmaxsUbIgylzb7Av.png', 'media_size' => '159298', 'media_type' => 'image', 'media_name' => 'ai-featured-video-img-4.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:36', 'updated_at' => '2024-03-20 10:23:36', 'deleted_at' => NULL),
            array('id' => '77', 'user_id' => '1', 'media_file' => 'uploads/media/76CwWSrcqNpKwOC4xyBdIcLaqHPZkfvGZXYjO93y.png', 'media_size' => '43791', 'media_type' => 'image', 'media_name' => 'ai-image-slide-5.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:37', 'updated_at' => '2024-03-20 10:23:37', 'deleted_at' => NULL),
            array('id' => '78', 'user_id' => '1', 'media_file' => 'uploads/media/s6Cejmb02gSLbpOYiZzFQR3hlhkpwhyS4e1oIpNQ.png', 'media_size' => '34001', 'media_type' => 'image', 'media_name' => 'ai-image-slide-6.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:37', 'updated_at' => '2024-03-20 10:23:37', 'deleted_at' => NULL),
            array('id' => '79', 'user_id' => '1', 'media_file' => 'uploads/media/LpfohnS7fNJ98uBaLyBB5lf8D0xZNO8R1SZL25bQ.png', 'media_size' => '34840', 'media_type' => 'image', 'media_name' => 'ai-image-slide-9.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:37', 'updated_at' => '2024-03-20 10:23:37', 'deleted_at' => NULL),
            array('id' => '80', 'user_id' => '1', 'media_file' => 'uploads/media/7Quhoi9MaqmENZ6hQjnkyUuMkCyge70ZPbJdQ7zk.png', 'media_size' => '38299', 'media_type' => 'image', 'media_name' => 'ai-image-slide-10.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:37', 'updated_at' => '2024-03-20 10:23:37', 'deleted_at' => NULL),
            array('id' => '81', 'user_id' => '1', 'media_file' => 'uploads/media/QMHd768U8eoUxuQoK2J9h1CupxsmXyxcE9XlfMFK.png', 'media_size' => '32728', 'media_type' => 'image', 'media_name' => 'ai-image-slide-11.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:37', 'updated_at' => '2024-03-20 10:23:37', 'deleted_at' => NULL),
            array('id' => '82', 'user_id' => '1', 'media_file' => 'uploads/media/92Rikf03wOrWggAeRm8PQCZfBzRtMJLBrwjAbTTU.png', 'media_size' => '41043', 'media_type' => 'image', 'media_name' => 'ai-image-slide-12.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:37', 'updated_at' => '2024-03-20 10:23:37', 'deleted_at' => NULL),
            array('id' => '83', 'user_id' => '1', 'media_file' => 'uploads/media/FlSHC8qUW5eVMOEWZc1jtJdwqeBQ8QNJWbPyXurI.png', 'media_size' => '48369', 'media_type' => 'image', 'media_name' => 'ai-image-slide-13.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:37', 'updated_at' => '2024-03-20 10:23:37', 'deleted_at' => NULL),
            array('id' => '84', 'user_id' => '1', 'media_file' => 'uploads/media/9WSCLmtY3vWtsK3Nt7R4UsLWEyXamk4M08qs1Kev.png', 'media_size' => '29380', 'media_type' => 'image', 'media_name' => 'ai-image-slide-15.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:37', 'updated_at' => '2024-03-20 10:23:37', 'deleted_at' => NULL),
            array('id' => '85', 'user_id' => '1', 'media_file' => 'uploads/media/ffFR6R4lm6UlPiDs5kXbGUpFGrPawAIVM4N0ux3S.png', 'media_size' => '32098', 'media_type' => 'image', 'media_name' => 'ai-image-slide-16.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:37', 'updated_at' => '2024-03-20 10:23:37', 'deleted_at' => NULL),
            array('id' => '86', 'user_id' => '1', 'media_file' => 'uploads/media/CW4Mdr8igX30Q3m02ntRLAonfjig44K7SstXSQOx.png', 'media_size' => '222564', 'media_type' => 'image', 'media_name' => 'insight-1.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:37', 'updated_at' => '2024-03-20 10:23:37', 'deleted_at' => NULL),
            array('id' => '87', 'user_id' => '1', 'media_file' => 'uploads/media/ejOyRxBK6P3kE6Vr7e9FTduGhTwJ4RCKangRzEbK.png', 'media_size' => '165383', 'media_type' => 'image', 'media_name' => 'insight-2.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:38', 'updated_at' => '2024-03-20 10:23:38', 'deleted_at' => NULL),
            array('id' => '88', 'user_id' => '1', 'media_file' => 'uploads/media/lhAEEpt9G0pMdZfAH6spBcr7rYtEphF9bVThs1FR.png', 'media_size' => '239360', 'media_type' => 'image', 'media_name' => 'insight-3.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:38', 'updated_at' => '2024-03-20 10:23:38', 'deleted_at' => NULL),
            array('id' => '89', 'user_id' => '1', 'media_file' => 'uploads/media/NpyhziYxqZfYX1hrPCPDLLDgv5ZvqJT5GzahL6yt.png', 'media_size' => '145029', 'media_type' => 'image', 'media_name' => 'popular-post-1.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:38', 'updated_at' => '2024-03-20 10:23:38', 'deleted_at' => NULL),
            array('id' => '90', 'user_id' => '1', 'media_file' => 'uploads/media/rgD3lq6imYfhJEsTF5EZd69ht3VnbPb3ITxiEDPM.png', 'media_size' => '133016', 'media_type' => 'image', 'media_name' => 'popular-post-2.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:38', 'updated_at' => '2024-03-20 10:23:38', 'deleted_at' => NULL),
            array('id' => '91', 'user_id' => '1', 'media_file' => 'uploads/media/T4Vzc5QJ3ya77Z4IOcwHocZUxIxsaNiEeEOFGCim.png', 'media_size' => '103769', 'media_type' => 'image', 'media_name' => 'popular-post-3.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:38', 'updated_at' => '2024-03-20 10:23:38', 'deleted_at' => NULL),
            array('id' => '92', 'user_id' => '1', 'media_file' => 'uploads/media/MLz5akOToNx4ET1T4CojXeEvu9WH6QhgP9cOhY1O.png', 'media_size' => '159576', 'media_type' => 'image', 'media_name' => 'popular-post-4.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:38', 'updated_at' => '2024-03-20 10:23:38', 'deleted_at' => NULL),
            array('id' => '93', 'user_id' => '1', 'media_file' => 'uploads/media/1DLUMsmNyGy8PeF50xteMxGUSQI2AoBkVMdFKV1M.png', 'media_size' => '132077', 'media_type' => 'image', 'media_name' => 'popular-post-5.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:38', 'updated_at' => '2024-03-20 10:23:38', 'deleted_at' => NULL),
            array('id' => '94', 'user_id' => '1', 'media_file' => 'uploads/media/AbWfW3NOns772PGy2pL6pe8u1vXVWVFStUMqowol.png', 'media_size' => '161328', 'media_type' => 'image', 'media_name' => 'popular-post-6.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:38', 'updated_at' => '2024-03-20 10:23:38', 'deleted_at' => NULL),
            array('id' => '95', 'user_id' => '1', 'media_file' => 'uploads/media/7Eve5kxuIu77CjcO8453V7HDdRGzHcvkbbT1ceNG.png', 'media_size' => '129005', 'media_type' => 'image', 'media_name' => 'popular-post-7.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:39', 'updated_at' => '2024-03-20 10:23:39', 'deleted_at' => NULL),
            array('id' => '96', 'user_id' => '1', 'media_file' => 'uploads/media/R0PTaXlhzedIeJx4xST1Ujlv7FBRV8A2UscdsDim.png', 'media_size' => '156284', 'media_type' => 'image', 'media_name' => 'popular-post-8.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:39', 'updated_at' => '2024-03-20 10:23:39', 'deleted_at' => NULL),
            array('id' => '97', 'user_id' => '1', 'media_file' => 'uploads/media/eIzd6hHZOalcnwrPMqaHU7AqQuZqjY05u8pIoxHn.png', 'media_size' => '153036', 'media_type' => 'image', 'media_name' => 'popular-post-9.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:39', 'updated_at' => '2024-03-20 10:23:39', 'deleted_at' => NULL),
            array('id' => '98', 'user_id' => '1', 'media_file' => 'uploads/media/YmXrreIeXCCjjROng5N58MnZFB7AycRvQZgdQcPH.png', 'media_size' => '141882', 'media_type' => 'image', 'media_name' => 'popular-post-10.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:39', 'updated_at' => '2024-03-20 10:23:39', 'deleted_at' => NULL),
            array('id' => '99', 'user_id' => '1', 'media_file' => 'uploads/media/z6ghEhPROsxDnURSgtpNo83eBmhBMkbG5ezD5M3E.png', 'media_size' => '136274', 'media_type' => 'image', 'media_name' => 'popular-post-11.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:39', 'updated_at' => '2024-03-20 10:23:39', 'deleted_at' => NULL),
            array('id' => '100', 'user_id' => '1', 'media_file' => 'uploads/media/cHfOYmId3reG8spUc0PxaGG742BRXEWauTn4rSLa.png', 'media_size' => '119588', 'media_type' => 'image', 'media_name' => 'popular-post-12.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:39', 'updated_at' => '2024-03-20 10:23:39', 'deleted_at' => NULL),
            array('id' => '101', 'user_id' => '1', 'media_file' => 'uploads/media/ha9iyqxBIjlZbXOBBAcMNYA4wpzqbsJOTtAx3V18.png', 'media_size' => '34508', 'media_type' => 'image', 'media_name' => 'Fun or Quote.png', 'media_extension' => 'png', 'created_at' => '2024-03-20 10:23:39', 'updated_at' => '2024-03-20 10:23:39', 'deleted_at' => NULL)
        );

        foreach ($media_managers as $media_manager) {
            $mm = MediaManager::where('media_file', $media_manager['media_file'])->first();
            if (!$mm) {
                $mm = new MediaManager();
            }
            $mm->user_id = $media_manager['user_id'];
            $mm->media_file = $media_manager['media_file'];
            $mm->media_size = $media_manager['media_size'];
            $mm->media_type = $media_manager['media_type'];
            $mm->media_name = $media_manager['media_name'];
            $mm->media_extension = $media_manager['media_extension'];
            $mm->updated_at = $media_manager['updated_at'];
            $mm->created_at = $media_manager['created_at'];
            $mm->deleted_at = $media_manager['deleted_at'];
            $mm->save();
        }
    }
} 
